/**
 * Renders the introspector's JSON into Docusaurus-compatible Markdown pages.
 *
 * Page shape deliberately matches @vantagecompute/docusaurus-plugin-godoc so a reader
 * moving between a Go spoke and a Python spoke on docs.vantagecompute.ai sees the same
 * furniture: the same frontmatter keys, the same "do not edit" marker, an Overview
 * section, then Constants, Classes and Functions, and an index carrying a package table.
 */

/** Escapes the characters that would otherwise break out of a Markdown table cell. */
function escapeCell(text) {
  return String(text).replace(/\|/g, '\\|').replace(/\n+/g, ' ');
}

/**
 * Renders a docstring for placement in a Markdown body.
 *
 * Docstrings are emitted verbatim. They are authored as prose by the same people who
 * wrote the code, and reflowing or re-wrapping them here would silently mangle the
 * indented blocks, tables and reStructuredText roles that many of them contain.
 */
function renderDoc(doc, lines) {
  if (!doc) {
    return;
  }
  lines.push(doc);
  lines.push('');
}

/** Renders one module's page. */
function renderModulePage(mod, label) {
  const lines = [];

  lines.push('---');
  lines.push(`title: "Module: ${label}"`);
  lines.push(`description: "Python API documentation for ${mod.module}"`);
  lines.push('---');
  lines.push('');
  lines.push(`# Module \`${label}\``);
  lines.push('');
  lines.push('{/* Auto-generated by @vantagecompute/docusaurus-plugin-pydoc. Do not edit manually. */}');
  lines.push('');
  lines.push(`Source: \`${mod.source}\``);
  lines.push('');

  if (mod.overview) {
    lines.push('## Overview');
    lines.push('');
    renderDoc(mod.overview, lines);
  }

  if (mod.constants.length > 0) {
    lines.push('## Constants');
    lines.push('');
    for (const constant of mod.constants) {
      const annotation = constant.annotation ? `: ${constant.annotation}` : '';
      const value = constant.value ? ` = ${constant.value}` : '';
      lines.push('```python');
      lines.push(`${constant.name}${annotation}${value}`);
      lines.push('```');
      lines.push('');
    }
  }

  if (mod.classes.length > 0) {
    lines.push('## Classes');
    lines.push('');
    for (const cls of mod.classes) {
      const bases = cls.bases.length > 0 ? `(${cls.bases.join(', ')})` : '';
      lines.push(`### ${cls.name}`);
      lines.push('');
      for (const decorator of cls.decorators) {
        lines.push('```python');
        lines.push(`@${decorator}`);
        lines.push('```');
        lines.push('');
      }
      lines.push('```python');
      lines.push(`class ${cls.name}${bases}`);
      lines.push('```');
      lines.push('');
      renderDoc(cls.doc, lines);

      if (cls.attributes.length > 0) {
        lines.push('| Attribute | Type | Default |');
        lines.push('|-----------|------|---------|');
        for (const attribute of cls.attributes) {
          const dflt = attribute.default ? `\`${escapeCell(attribute.default)}\`` : '';
          lines.push(`| \`${attribute.name}\` | \`${escapeCell(attribute.annotation)}\` | ${dflt} |`);
        }
        lines.push('');
      }

      for (const method of cls.methods) {
        const prefix = method.is_async ? 'async def' : 'def';
        lines.push(`#### ${cls.name}.${method.name}`);
        lines.push('');
        lines.push('```python');
        lines.push(`${prefix} ${method.name}${method.signature}`);
        lines.push('```');
        lines.push('');
        renderDoc(method.doc, lines);
      }
    }
  }

  if (mod.functions.length > 0) {
    lines.push('## Functions');
    lines.push('');
    for (const fn of mod.functions) {
      const prefix = fn.is_async ? 'async def' : 'def';
      lines.push(`### ${fn.name}`);
      lines.push('');
      lines.push('```python');
      lines.push(`${prefix} ${fn.name}${fn.signature}`);
      lines.push('```');
      lines.push('');
      renderDoc(fn.doc, lines);
    }
  }

  return lines.join('\n');
}

/**
 * Renders the index page.
 *
 * The package table's row shape is load-bearing for consumers that verify a docs build
 * really produced a reference rather than an empty shell: a row renders to
 * `>name</a></td>` in the built HTML, which is greppable in a way a sidebar entry is not.
 */
function renderIndexPage(moduleDocs) {
  const lines = [];

  lines.push('---');
  lines.push('title: SDK Reference');
  lines.push('description: "Auto-generated Python API documentation"');
  lines.push('---');
  lines.push('');
  lines.push('# SDK Reference');
  lines.push('');
  lines.push('{/* Auto-generated by @vantagecompute/docusaurus-plugin-pydoc. Do not edit manually. */}');
  lines.push('');
  lines.push('Auto-generated from docstrings in the source.');
  lines.push('');
  lines.push('## Modules');
  lines.push('');
  lines.push('| Module | Classes | Functions | Description |');
  lines.push('|--------|---------|-----------|-------------|');

  for (const mod of moduleDocs) {
    const description = mod.overview ? escapeCell(mod.overview.split('\n')[0]).substring(0, 80) : '';
    lines.push(`| [${mod.label}](./${mod.filename}) | ${mod.classes} | ${mod.functions} | ${description} |`);
  }

  lines.push('');
  lines.push('## Regenerating');
  lines.push('');
  lines.push('These pages are generated at build time by `@vantagecompute/docusaurus-plugin-pydoc`,');
  lines.push('which reads the source with `ast` and never imports it. To regenerate manually:');
  lines.push('');
  lines.push('```bash');
  lines.push('yarn build');
  lines.push('```');
  lines.push('');

  return lines.join('\n');
}

module.exports = {renderModulePage, renderIndexPage};
